version: '3.4'

services:
  everbridge.databaseperformancetest:
    image: ${DOCKER_REGISTRY-}everbridgedatabaseperformancetest
    build:
      context: .
      dockerfile: Dockerfile

  Mongo:
    image: mongo:latest
    ports:
      - "12000:27017"

  mssqlserver:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    deploy:
     resources: 
      limits: 
        memory: 500M  # Use at most 50 MB of RAM
    #networks:
    #  - es-net
    ports:
      - 9200:9200
#networks:
#  es-net:
#    driver: bridge